name: VANTAGE__WEB-DASHBOARD-DEPLOYMENT

on:
  pull_request:
    types: [ closed ]
    branches:
      - production

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment:
      production
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm i -g pnpm@latest

      - name: Install Dependencies
        run: pnpm install

      - name: Build Image
        run: docker build -t ghcr.io/${{github.actor}}/vantage__web-dashboard:v0.1 .

      - name: Login to Registry
        run: "echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{github.actor}} --password-stdin"

      - name: Push Image to Registry
        run: docker push ghcr.io/${{github.actor}}/vantage__web-dashboard:v0.1
