name: VANTAGE__WEB-DASHBOARD DEPLOYMENT

on:
  pull_request:
    types: [ closed ]
    branches:
      - production

jobs:
  build-and-push-to-ghcr:
    runs-on: ubuntu-latest
    environment: production
    env:
      DOCKER_IMAGE_TAG: "ghcr.io/${{github.actor}}/vantage__web-dashboard:${{github.sha}}"
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm i -g pnpm@latest

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Image
        run: docker build -t ${{env.DOCKER_IMAGE_TAG}} .

      - name: Login to Registry
        run: "echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{github.actor}} --password-stdin"

      - name: Push Image to Registry
        run: docker push ${{env.DOCKER_IMAGE_TAG}}

  deploy-to-gcloud:
    runs-on: ubuntu-latest
    environment: production
    env:
      DOCKER_IMAGE_NAME: ${{secrets.GCLOUD_ARTIFACT_REGISTRY_LOCATION}}-docker.pkg.dev/${{secrets.GCLOUD_PROJECT_ID}}/${{secrets.GCLOUD_ARTIFACT_REPOSITORY_NAME}}/vantage__dashboard:${{github.sha}}
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: gcloud-auth
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{secrets.GCLOUD_CREDENTIALS_JSON}}
          token_format: 'access_token'

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker
        run: gcloud auth configure-docker ${{secrets.GCLOUD_ARTIFACT_REGISTRY_LOCATION}}-docker.pkg.dev

      - name: Docker Login
        uses: docker/login-action@v4
        with:
          username: oauth2accesstoken
          password: ${{steps.gcloud-auth.outputs.access_token}}
          registry: ${{secrets.GCLOUD_ARTIFACT_REGISTRY_LOCATION}}-docker.pkg.dev

      - name: Build Image
        run: docker build -t ${{env.DOCKER_IMAGE_NAME}} .

      - name: Push Image
        run: docker push ${{env.DOCKER_IMAGE_NAME}}

      - name: Run Image
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: vantage-web-dashboard
          image: ${{env.DOCKER_IMAGE_NAME}}
          region: asia-southeast1
          env_vars: |
            VITE_API_URL=${{vars.VANTAGE_API_URL}}
            VITE_SUPABASE_URL=${{secrets.SUPABASE_URL}}
            VITE_SUPABASE_PUBLISHABLE_KEY=${{secrets.SUPABASE_PUBLISHABLE_KEY}}
            VITE_SUPABSE_PROJECT_ID=${{secrets.SUPABASE_PROJECT_ID}}
            SUPABSE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET=${{secrets.SUPABSE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET}}
            VITE_SUPABSE_STORAGE_BUCKET_ID=${{secrets.SUPABSE_STORAGE_BUCKET_ID}}
