name: VANTAGE__WEB-DASHBOARD DEPLOYMENT

on:
  pull_request:
    types: [ closed ]
    branches:
      - production

jobs:
  build-and-push-to-ghcr:
    runs-on: ubuntu-latest
    environment:
      production
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm i -g pnpm@latest

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Image
        run: docker build -t ghcr.io/${{github.actor}}/vantage__web-dashboard:${{github.sha}} .

      - name: Login to Registry
        run: "echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{github.actor}} --password-stdin"

      - name: Push Image to Registry
        run: docker push ghcr.io/${{github.actor}}/vantage__web-dashboard:v0.1

  deploy-to-gcloud:
    runs-on: ubuntu-latest
    environment: production
    env:
      DOCKER_IMAGE_NAME: ${{secrets.GCLOUD_ARTIFACT_REGISTRY_LOCATION}}-docker.pkg.dev/${{secrets.GCLOUD_PROJECT_ID}}/${{secrets.GCLOUD_ARTIFACT_REPOSITORY_NAME}}/vantage__dashboard:${{github.sha}}
    permissions:
      contents: read
      id-token: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{secrets.GCLOUD_CREDENTIALS_JSON}}

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker
        run: gcloud auth configure-docker ${{GCLOUD_ARTIFACT_REGISTRY_LOCATION}}-docker.pkg.dev

      - name: Build Image
        run: docker build -t ${{env.DOCKER_IMAGE_NAME}} .

      - name: Push Image
        run: docker push ${{env.DOCKER_IMAGE_NAME}}
