name: VANTAGE__WEB-DASHBOARD TEST

on:
  push:
    branches:
      - main

jobs:
  workflow-lint:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Lint Workflows
        uses: reviewdog/action-actionlint@v1.43.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}

  image-build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      integration
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Build
        run: docker build -t ghcr.io/${{github.actor}}/vantage__web-dashboard:v0.1 .